version: 2.1

jobs:
  build:
    macos:
      xcode: 14.1

    steps:
      - checkout
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 14 Pro
            SCAN_SCHEME: NewPass

workflows:
  build-and-test:
    jobs:
      - build

